//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Controls/GridBuildingControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GridBuildingControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GridBuildingControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GridBuildingControls"",
    ""maps"": [
        {
            ""name"": ""GridBuilding"",
            ""id"": ""9a7b6c6e-a3df-44e2-acbc-b0359e730ade"",
            ""actions"": [
                {
                    ""name"": ""Demolish"",
                    ""type"": ""Button"",
                    ""id"": ""a53dfc1b-5666-4bcb-b6e3-ae22d472d0f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Build"",
                    ""type"": ""Button"",
                    ""id"": ""cc16ec99-d2e8-4c2b-8b66-b0f46336412d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""26a930d9-d14f-459f-866c-363605b2cf32"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleBuildMenu"",
                    ""type"": ""Button"",
                    ""id"": ""528686b1-2033-4f69-ab76-8dca4ddaa921"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey1"",
                    ""type"": ""Button"",
                    ""id"": ""b2d0d12f-5905-4d4f-8508-772051b48309"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey2"",
                    ""type"": ""Button"",
                    ""id"": ""7e49a84d-056f-46b3-bc4d-efe8d81a72b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey3"",
                    ""type"": ""Button"",
                    ""id"": ""e422b14a-3a08-43f2-adc1-97391ab56ff5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey4"",
                    ""type"": ""Button"",
                    ""id"": ""c85726d9-242d-4b81-8cfe-661a8ca72d5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey5"",
                    ""type"": ""Button"",
                    ""id"": ""bb626773-0c4b-4abc-a96c-543de242d0b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey6"",
                    ""type"": ""Button"",
                    ""id"": ""8401924b-dbde-4f27-827c-384173228a9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey7"",
                    ""type"": ""Button"",
                    ""id"": ""06a1c043-d74c-430f-8b97-a541a5080717"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey8"",
                    ""type"": ""Button"",
                    ""id"": ""af7283f5-8d2e-4c76-8f63-4d5a1768c25c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey9"",
                    ""type"": ""Button"",
                    ""id"": ""ad50456a-d553-44a6-8048-e6cde90cb7cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3e964024-1f68-4d47-aabe-620c747f4a6c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Demolish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b7217eb-d294-42df-aa80-3269680b1fb7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3644e18d-7d3f-4ec4-9278-5a90c95e8cb5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""ToggleBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01346685-958d-4a6c-a2c3-bbd04c77ae33"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Build"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed1b30ad-9213-4afb-9e9d-fffa84ec0202"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a617fda4-a958-4d03-a1c3-25193bf64db5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1eb5750e-f8d1-4da9-a36c-3fd4d7e275f1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5dd8a2d-04f6-43db-bbcd-e4eefd705db5"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae82a32d-4565-41d8-8f49-cb9fc3f05e55"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fb3416c-5d70-46fb-889a-1a7e7e77f783"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed3fb6de-a12b-4917-a1bf-a5d9c58641ba"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f001d3f-1320-429d-9f73-5243aedff6a7"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89bd1be5-bea9-4e9d-b6f2-532f48b0cedc"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse + Keyboard"",
            ""bindingGroup"": ""Mouse + Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // GridBuilding
        m_GridBuilding = asset.FindActionMap("GridBuilding", throwIfNotFound: true);
        m_GridBuilding_Demolish = m_GridBuilding.FindAction("Demolish", throwIfNotFound: true);
        m_GridBuilding_Build = m_GridBuilding.FindAction("Build", throwIfNotFound: true);
        m_GridBuilding_Rotate = m_GridBuilding.FindAction("Rotate", throwIfNotFound: true);
        m_GridBuilding_ToggleBuildMenu = m_GridBuilding.FindAction("ToggleBuildMenu", throwIfNotFound: true);
        m_GridBuilding_NumberKey1 = m_GridBuilding.FindAction("NumberKey1", throwIfNotFound: true);
        m_GridBuilding_NumberKey2 = m_GridBuilding.FindAction("NumberKey2", throwIfNotFound: true);
        m_GridBuilding_NumberKey3 = m_GridBuilding.FindAction("NumberKey3", throwIfNotFound: true);
        m_GridBuilding_NumberKey4 = m_GridBuilding.FindAction("NumberKey4", throwIfNotFound: true);
        m_GridBuilding_NumberKey5 = m_GridBuilding.FindAction("NumberKey5", throwIfNotFound: true);
        m_GridBuilding_NumberKey6 = m_GridBuilding.FindAction("NumberKey6", throwIfNotFound: true);
        m_GridBuilding_NumberKey7 = m_GridBuilding.FindAction("NumberKey7", throwIfNotFound: true);
        m_GridBuilding_NumberKey8 = m_GridBuilding.FindAction("NumberKey8", throwIfNotFound: true);
        m_GridBuilding_NumberKey9 = m_GridBuilding.FindAction("NumberKey9", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GridBuilding
    private readonly InputActionMap m_GridBuilding;
    private List<IGridBuildingActions> m_GridBuildingActionsCallbackInterfaces = new List<IGridBuildingActions>();
    private readonly InputAction m_GridBuilding_Demolish;
    private readonly InputAction m_GridBuilding_Build;
    private readonly InputAction m_GridBuilding_Rotate;
    private readonly InputAction m_GridBuilding_ToggleBuildMenu;
    private readonly InputAction m_GridBuilding_NumberKey1;
    private readonly InputAction m_GridBuilding_NumberKey2;
    private readonly InputAction m_GridBuilding_NumberKey3;
    private readonly InputAction m_GridBuilding_NumberKey4;
    private readonly InputAction m_GridBuilding_NumberKey5;
    private readonly InputAction m_GridBuilding_NumberKey6;
    private readonly InputAction m_GridBuilding_NumberKey7;
    private readonly InputAction m_GridBuilding_NumberKey8;
    private readonly InputAction m_GridBuilding_NumberKey9;
    public struct GridBuildingActions
    {
        private @GridBuildingControls m_Wrapper;
        public GridBuildingActions(@GridBuildingControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Demolish => m_Wrapper.m_GridBuilding_Demolish;
        public InputAction @Build => m_Wrapper.m_GridBuilding_Build;
        public InputAction @Rotate => m_Wrapper.m_GridBuilding_Rotate;
        public InputAction @ToggleBuildMenu => m_Wrapper.m_GridBuilding_ToggleBuildMenu;
        public InputAction @NumberKey1 => m_Wrapper.m_GridBuilding_NumberKey1;
        public InputAction @NumberKey2 => m_Wrapper.m_GridBuilding_NumberKey2;
        public InputAction @NumberKey3 => m_Wrapper.m_GridBuilding_NumberKey3;
        public InputAction @NumberKey4 => m_Wrapper.m_GridBuilding_NumberKey4;
        public InputAction @NumberKey5 => m_Wrapper.m_GridBuilding_NumberKey5;
        public InputAction @NumberKey6 => m_Wrapper.m_GridBuilding_NumberKey6;
        public InputAction @NumberKey7 => m_Wrapper.m_GridBuilding_NumberKey7;
        public InputAction @NumberKey8 => m_Wrapper.m_GridBuilding_NumberKey8;
        public InputAction @NumberKey9 => m_Wrapper.m_GridBuilding_NumberKey9;
        public InputActionMap Get() { return m_Wrapper.m_GridBuilding; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GridBuildingActions set) { return set.Get(); }
        public void AddCallbacks(IGridBuildingActions instance)
        {
            if (instance == null || m_Wrapper.m_GridBuildingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GridBuildingActionsCallbackInterfaces.Add(instance);
            @Demolish.started += instance.OnDemolish;
            @Demolish.performed += instance.OnDemolish;
            @Demolish.canceled += instance.OnDemolish;
            @Build.started += instance.OnBuild;
            @Build.performed += instance.OnBuild;
            @Build.canceled += instance.OnBuild;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @ToggleBuildMenu.started += instance.OnToggleBuildMenu;
            @ToggleBuildMenu.performed += instance.OnToggleBuildMenu;
            @ToggleBuildMenu.canceled += instance.OnToggleBuildMenu;
            @NumberKey1.started += instance.OnNumberKey1;
            @NumberKey1.performed += instance.OnNumberKey1;
            @NumberKey1.canceled += instance.OnNumberKey1;
            @NumberKey2.started += instance.OnNumberKey2;
            @NumberKey2.performed += instance.OnNumberKey2;
            @NumberKey2.canceled += instance.OnNumberKey2;
            @NumberKey3.started += instance.OnNumberKey3;
            @NumberKey3.performed += instance.OnNumberKey3;
            @NumberKey3.canceled += instance.OnNumberKey3;
            @NumberKey4.started += instance.OnNumberKey4;
            @NumberKey4.performed += instance.OnNumberKey4;
            @NumberKey4.canceled += instance.OnNumberKey4;
            @NumberKey5.started += instance.OnNumberKey5;
            @NumberKey5.performed += instance.OnNumberKey5;
            @NumberKey5.canceled += instance.OnNumberKey5;
            @NumberKey6.started += instance.OnNumberKey6;
            @NumberKey6.performed += instance.OnNumberKey6;
            @NumberKey6.canceled += instance.OnNumberKey6;
            @NumberKey7.started += instance.OnNumberKey7;
            @NumberKey7.performed += instance.OnNumberKey7;
            @NumberKey7.canceled += instance.OnNumberKey7;
            @NumberKey8.started += instance.OnNumberKey8;
            @NumberKey8.performed += instance.OnNumberKey8;
            @NumberKey8.canceled += instance.OnNumberKey8;
            @NumberKey9.started += instance.OnNumberKey9;
            @NumberKey9.performed += instance.OnNumberKey9;
            @NumberKey9.canceled += instance.OnNumberKey9;
        }

        private void UnregisterCallbacks(IGridBuildingActions instance)
        {
            @Demolish.started -= instance.OnDemolish;
            @Demolish.performed -= instance.OnDemolish;
            @Demolish.canceled -= instance.OnDemolish;
            @Build.started -= instance.OnBuild;
            @Build.performed -= instance.OnBuild;
            @Build.canceled -= instance.OnBuild;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @ToggleBuildMenu.started -= instance.OnToggleBuildMenu;
            @ToggleBuildMenu.performed -= instance.OnToggleBuildMenu;
            @ToggleBuildMenu.canceled -= instance.OnToggleBuildMenu;
            @NumberKey1.started -= instance.OnNumberKey1;
            @NumberKey1.performed -= instance.OnNumberKey1;
            @NumberKey1.canceled -= instance.OnNumberKey1;
            @NumberKey2.started -= instance.OnNumberKey2;
            @NumberKey2.performed -= instance.OnNumberKey2;
            @NumberKey2.canceled -= instance.OnNumberKey2;
            @NumberKey3.started -= instance.OnNumberKey3;
            @NumberKey3.performed -= instance.OnNumberKey3;
            @NumberKey3.canceled -= instance.OnNumberKey3;
            @NumberKey4.started -= instance.OnNumberKey4;
            @NumberKey4.performed -= instance.OnNumberKey4;
            @NumberKey4.canceled -= instance.OnNumberKey4;
            @NumberKey5.started -= instance.OnNumberKey5;
            @NumberKey5.performed -= instance.OnNumberKey5;
            @NumberKey5.canceled -= instance.OnNumberKey5;
            @NumberKey6.started -= instance.OnNumberKey6;
            @NumberKey6.performed -= instance.OnNumberKey6;
            @NumberKey6.canceled -= instance.OnNumberKey6;
            @NumberKey7.started -= instance.OnNumberKey7;
            @NumberKey7.performed -= instance.OnNumberKey7;
            @NumberKey7.canceled -= instance.OnNumberKey7;
            @NumberKey8.started -= instance.OnNumberKey8;
            @NumberKey8.performed -= instance.OnNumberKey8;
            @NumberKey8.canceled -= instance.OnNumberKey8;
            @NumberKey9.started -= instance.OnNumberKey9;
            @NumberKey9.performed -= instance.OnNumberKey9;
            @NumberKey9.canceled -= instance.OnNumberKey9;
        }

        public void RemoveCallbacks(IGridBuildingActions instance)
        {
            if (m_Wrapper.m_GridBuildingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGridBuildingActions instance)
        {
            foreach (var item in m_Wrapper.m_GridBuildingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GridBuildingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GridBuildingActions @GridBuilding => new GridBuildingActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse + Keyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    public interface IGridBuildingActions
    {
        void OnDemolish(InputAction.CallbackContext context);
        void OnBuild(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnToggleBuildMenu(InputAction.CallbackContext context);
        void OnNumberKey1(InputAction.CallbackContext context);
        void OnNumberKey2(InputAction.CallbackContext context);
        void OnNumberKey3(InputAction.CallbackContext context);
        void OnNumberKey4(InputAction.CallbackContext context);
        void OnNumberKey5(InputAction.CallbackContext context);
        void OnNumberKey6(InputAction.CallbackContext context);
        void OnNumberKey7(InputAction.CallbackContext context);
        void OnNumberKey8(InputAction.CallbackContext context);
        void OnNumberKey9(InputAction.CallbackContext context);
    }
}
