//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Controls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""e2646380-1b81-4e6f-b300-80c16be85d54"",
            ""actions"": [
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""472b3452-dd33-4527-91b4-26f3b15ae7e8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8ccc06d1-824f-49c3-bc31-63df342e7533"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fcdac0f1-da6f-4342-98da-3de0786e9c03"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cb069d0f-8fe2-4cc3-be02-5625e6c2b74b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""54cc903d-e4c4-4bc9-95ba-646c4dd51041"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7fe56cdc-06e6-4491-97e6-734620d97318"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b66a10a5-bad2-4bd8-a6c0-163a7d3b2919"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48db87c4-ece6-4d6e-bca6-a7947b949b03"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58c56586-714b-4405-8615-90b0a534327a"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2bde36a-5c48-4e2c-8585-e3fae3bc25d9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GroundMovement"",
            ""id"": ""13f97ea6-da82-46eb-8516-1ab019db8717"",
            ""actions"": [
                {
                    ""name"": ""HorizontalMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""096c913d-7a22-4888-890c-94c8d2ca2f68"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""4a80ad8f-3859-4230-87d2-1fd6544e4228"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""cc8a7675-c6fa-438d-9110-8df20801ddd2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Button"",
                    ""id"": ""d6b30bc4-39b4-4edd-88f4-74b9cc85cf5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""dd9ff5b2-d21a-4092-944b-7a63cae316e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""bb73270e-c869-4794-b6dc-c17a13064bdf"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""37806c69-0b26-4310-b417-643edc7d64ef"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ca63bb5c-7c84-4d6e-a279-ca876d4b2433"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5fb7eaa4-3e7a-4b36-b673-24d205a665cc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""acd97f68-8e53-4247-83d3-d916d7484111"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3a232a77-d7b2-4346-8897-58dbec863f79"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dedef0e3-ddb4-4912-8480-74fc86572db1"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b613de7-eeac-44e2-98a5-3554138ad582"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07576527-c763-47d7-93d6-53e9efe7a3fd"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerMechanics"",
            ""id"": ""95b5f076-2a3c-4bb0-9462-00cc9a9c7aa7"",
            ""actions"": [
                {
                    ""name"": ""MouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a991e6c0-e66c-4bb7-8401-19f2d5affbdc"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ea774810-ed56-4c5d-967c-66a0c744a5c0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraSwitch"",
                    ""type"": ""Button"",
                    ""id"": ""f88d6419-65e1-4b6a-852b-df7da316c7a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""47f5af04-6812-4882-acee-b0066f9b61c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""89004766-79fa-4ecb-a8c9-7c53df1d003c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey1"",
                    ""type"": ""Button"",
                    ""id"": ""a46ad9bf-4fad-40f6-95fc-940d2ffe447d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey2"",
                    ""type"": ""Button"",
                    ""id"": ""ed9c334f-56a9-45db-a7e1-787869cbf53d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey3"",
                    ""type"": ""Button"",
                    ""id"": ""fe2a4374-b634-4ccd-8a42-6aa68b874bbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey4"",
                    ""type"": ""Button"",
                    ""id"": ""c562fe5b-94ee-4aa8-a5ff-bf6a34702b42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey5"",
                    ""type"": ""Button"",
                    ""id"": ""d81de83a-8b0d-473b-bd0b-a9e6fbf2e248"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey6"",
                    ""type"": ""Button"",
                    ""id"": ""57a740c3-7f73-4d93-9fe1-4049cc639c03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey7"",
                    ""type"": ""Button"",
                    ""id"": ""309ade35-f455-4719-a721-36135f1e6820"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey8"",
                    ""type"": ""Button"",
                    ""id"": ""47301c51-5506-47ff-9ec2-90759336e9fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberKey9"",
                    ""type"": ""Button"",
                    ""id"": ""1a0f74ef-4a7c-4385-a765-0528a97ab6eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockOn"",
                    ""type"": ""Button"",
                    ""id"": ""f7a7c611-4620-44a9-bbda-f3d9af1c83ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlipCameraAlignment"",
                    ""type"": ""Button"",
                    ""id"": ""7fe55177-4eb4-4799-ae5e-fff2afe23292"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""8bb18766-fc91-49af-b170-8858e3f6bd40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""7389acf2-a331-48df-b83e-1576f4e5970d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TertiaryInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""9fa77cdd-a697-4bb9-ad00-d55f0af40125"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sheath"",
                    ""type"": ""Button"",
                    ""id"": ""2b34baa4-0567-440c-a9a2-e7d2a3fd71a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8348e412-617d-409e-8ad5-411756c31ea7"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc7f47d0-b80b-454f-a7e1-960c8231f99d"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cf66f00-c9b7-4475-8919-2856610b9710"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""CameraSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""848f29e1-931f-4519-8a2a-c39e064dc424"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""ToggleBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9070bd9c-9848-474d-9a43-16fc21810867"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f530b62e-5977-4560-bb75-d0e1333fcf58"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6225071a-039c-41b0-9ebf-a3c8fcfeb913"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3490aea-b0c8-4c15-8c16-de0fb8108b61"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a5dd4c-5691-45a3-9f34-580e14e18a0c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af53986e-28c6-48b9-9024-b1ad87d3074a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e86243d-5021-4998-a8ed-434a1ea001ab"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e0951f8-5a94-4c12-ba04-5106342fa7c3"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02aa0148-e43f-4487-935e-04533b127dac"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48221d12-bd19-499b-9ffb-75209042a87b"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""NumberKey9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a343eda-5ac7-420a-af43-a0c93fd8139d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""787f472e-55f5-437c-8ef1-66ef1a981000"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlipCameraAlignment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8f90f20-2e4d-493f-9b45-c2e3af10660f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""PrimaryInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1f026c1-7963-4d2f-8830-63dd6e40ac99"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""SecondaryInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e743fb47-ab73-4835-bf84-98622872d951"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""TertiaryInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""788972a8-ee00-4c67-9626-3b49aadb5be9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Sheath"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GridBuilding"",
            ""id"": ""9a7b6c6e-a3df-44e2-acbc-b0359e730ade"",
            ""actions"": [
                {
                    ""name"": ""Demolish"",
                    ""type"": ""Button"",
                    ""id"": ""a53dfc1b-5666-4bcb-b6e3-ae22d472d0f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Build"",
                    ""type"": ""Button"",
                    ""id"": ""cc16ec99-d2e8-4c2b-8b66-b0f46336412d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""26a930d9-d14f-459f-866c-363605b2cf32"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleBuildMenu"",
                    ""type"": ""Button"",
                    ""id"": ""528686b1-2033-4f69-ab76-8dca4ddaa921"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3e964024-1f68-4d47-aabe-620c747f4a6c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Demolish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b7217eb-d294-42df-aa80-3269680b1fb7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3644e18d-7d3f-4ec4-9278-5a90c95e8cb5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""ToggleBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01346685-958d-4a6c-a2c3-bbd04c77ae33"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse + Keyboard"",
                    ""action"": ""Build"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse + Keyboard"",
            ""bindingGroup"": ""Mouse + Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
        m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        // GroundMovement
        m_GroundMovement = asset.FindActionMap("GroundMovement", throwIfNotFound: true);
        m_GroundMovement_HorizontalMovement = m_GroundMovement.FindAction("HorizontalMovement", throwIfNotFound: true);
        m_GroundMovement_Jump = m_GroundMovement.FindAction("Jump", throwIfNotFound: true);
        m_GroundMovement_Crouch = m_GroundMovement.FindAction("Crouch", throwIfNotFound: true);
        m_GroundMovement_Walk = m_GroundMovement.FindAction("Walk", throwIfNotFound: true);
        m_GroundMovement_Sprint = m_GroundMovement.FindAction("Sprint", throwIfNotFound: true);
        // PlayerMechanics
        m_PlayerMechanics = asset.FindActionMap("PlayerMechanics", throwIfNotFound: true);
        m_PlayerMechanics_MouseX = m_PlayerMechanics.FindAction("MouseX", throwIfNotFound: true);
        m_PlayerMechanics_MouseY = m_PlayerMechanics.FindAction("MouseY", throwIfNotFound: true);
        m_PlayerMechanics_CameraSwitch = m_PlayerMechanics.FindAction("CameraSwitch", throwIfNotFound: true);
        m_PlayerMechanics_ToggleBuildMode = m_PlayerMechanics.FindAction("ToggleBuildMode", throwIfNotFound: true);
        m_PlayerMechanics_MouseScroll = m_PlayerMechanics.FindAction("MouseScroll", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey1 = m_PlayerMechanics.FindAction("NumberKey1", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey2 = m_PlayerMechanics.FindAction("NumberKey2", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey3 = m_PlayerMechanics.FindAction("NumberKey3", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey4 = m_PlayerMechanics.FindAction("NumberKey4", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey5 = m_PlayerMechanics.FindAction("NumberKey5", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey6 = m_PlayerMechanics.FindAction("NumberKey6", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey7 = m_PlayerMechanics.FindAction("NumberKey7", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey8 = m_PlayerMechanics.FindAction("NumberKey8", throwIfNotFound: true);
        m_PlayerMechanics_NumberKey9 = m_PlayerMechanics.FindAction("NumberKey9", throwIfNotFound: true);
        m_PlayerMechanics_LockOn = m_PlayerMechanics.FindAction("LockOn", throwIfNotFound: true);
        m_PlayerMechanics_FlipCameraAlignment = m_PlayerMechanics.FindAction("FlipCameraAlignment", throwIfNotFound: true);
        m_PlayerMechanics_PrimaryInteraction = m_PlayerMechanics.FindAction("PrimaryInteraction", throwIfNotFound: true);
        m_PlayerMechanics_SecondaryInteraction = m_PlayerMechanics.FindAction("SecondaryInteraction", throwIfNotFound: true);
        m_PlayerMechanics_TertiaryInteraction = m_PlayerMechanics.FindAction("TertiaryInteraction", throwIfNotFound: true);
        m_PlayerMechanics_Sheath = m_PlayerMechanics.FindAction("Sheath", throwIfNotFound: true);
        // GridBuilding
        m_GridBuilding = asset.FindActionMap("GridBuilding", throwIfNotFound: true);
        m_GridBuilding_Demolish = m_GridBuilding.FindAction("Demolish", throwIfNotFound: true);
        m_GridBuilding_Build = m_GridBuilding.FindAction("Build", throwIfNotFound: true);
        m_GridBuilding_Rotate = m_GridBuilding.FindAction("Rotate", throwIfNotFound: true);
        m_GridBuilding_ToggleBuildMenu = m_GridBuilding.FindAction("ToggleBuildMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Click;
    private readonly InputAction m_UI_ScrollWheel;
    private readonly InputAction m_UI_MiddleClick;
    private readonly InputAction m_UI_RightClick;
    public struct UIActions
    {
        private @PlayerControls m_Wrapper;
        public UIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Click => m_Wrapper.m_UI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // GroundMovement
    private readonly InputActionMap m_GroundMovement;
    private IGroundMovementActions m_GroundMovementActionsCallbackInterface;
    private readonly InputAction m_GroundMovement_HorizontalMovement;
    private readonly InputAction m_GroundMovement_Jump;
    private readonly InputAction m_GroundMovement_Crouch;
    private readonly InputAction m_GroundMovement_Walk;
    private readonly InputAction m_GroundMovement_Sprint;
    public struct GroundMovementActions
    {
        private @PlayerControls m_Wrapper;
        public GroundMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @HorizontalMovement => m_Wrapper.m_GroundMovement_HorizontalMovement;
        public InputAction @Jump => m_Wrapper.m_GroundMovement_Jump;
        public InputAction @Crouch => m_Wrapper.m_GroundMovement_Crouch;
        public InputAction @Walk => m_Wrapper.m_GroundMovement_Walk;
        public InputAction @Sprint => m_Wrapper.m_GroundMovement_Sprint;
        public InputActionMap Get() { return m_Wrapper.m_GroundMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GroundMovementActions set) { return set.Get(); }
        public void SetCallbacks(IGroundMovementActions instance)
        {
            if (m_Wrapper.m_GroundMovementActionsCallbackInterface != null)
            {
                @HorizontalMovement.started -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnHorizontalMovement;
                @HorizontalMovement.performed -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnHorizontalMovement;
                @HorizontalMovement.canceled -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnHorizontalMovement;
                @Jump.started -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnJump;
                @Crouch.started -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnCrouch;
                @Walk.started -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnWalk;
                @Sprint.started -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_GroundMovementActionsCallbackInterface.OnSprint;
            }
            m_Wrapper.m_GroundMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @HorizontalMovement.started += instance.OnHorizontalMovement;
                @HorizontalMovement.performed += instance.OnHorizontalMovement;
                @HorizontalMovement.canceled += instance.OnHorizontalMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
            }
        }
    }
    public GroundMovementActions @GroundMovement => new GroundMovementActions(this);

    // PlayerMechanics
    private readonly InputActionMap m_PlayerMechanics;
    private IPlayerMechanicsActions m_PlayerMechanicsActionsCallbackInterface;
    private readonly InputAction m_PlayerMechanics_MouseX;
    private readonly InputAction m_PlayerMechanics_MouseY;
    private readonly InputAction m_PlayerMechanics_CameraSwitch;
    private readonly InputAction m_PlayerMechanics_ToggleBuildMode;
    private readonly InputAction m_PlayerMechanics_MouseScroll;
    private readonly InputAction m_PlayerMechanics_NumberKey1;
    private readonly InputAction m_PlayerMechanics_NumberKey2;
    private readonly InputAction m_PlayerMechanics_NumberKey3;
    private readonly InputAction m_PlayerMechanics_NumberKey4;
    private readonly InputAction m_PlayerMechanics_NumberKey5;
    private readonly InputAction m_PlayerMechanics_NumberKey6;
    private readonly InputAction m_PlayerMechanics_NumberKey7;
    private readonly InputAction m_PlayerMechanics_NumberKey8;
    private readonly InputAction m_PlayerMechanics_NumberKey9;
    private readonly InputAction m_PlayerMechanics_LockOn;
    private readonly InputAction m_PlayerMechanics_FlipCameraAlignment;
    private readonly InputAction m_PlayerMechanics_PrimaryInteraction;
    private readonly InputAction m_PlayerMechanics_SecondaryInteraction;
    private readonly InputAction m_PlayerMechanics_TertiaryInteraction;
    private readonly InputAction m_PlayerMechanics_Sheath;
    public struct PlayerMechanicsActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerMechanicsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseX => m_Wrapper.m_PlayerMechanics_MouseX;
        public InputAction @MouseY => m_Wrapper.m_PlayerMechanics_MouseY;
        public InputAction @CameraSwitch => m_Wrapper.m_PlayerMechanics_CameraSwitch;
        public InputAction @ToggleBuildMode => m_Wrapper.m_PlayerMechanics_ToggleBuildMode;
        public InputAction @MouseScroll => m_Wrapper.m_PlayerMechanics_MouseScroll;
        public InputAction @NumberKey1 => m_Wrapper.m_PlayerMechanics_NumberKey1;
        public InputAction @NumberKey2 => m_Wrapper.m_PlayerMechanics_NumberKey2;
        public InputAction @NumberKey3 => m_Wrapper.m_PlayerMechanics_NumberKey3;
        public InputAction @NumberKey4 => m_Wrapper.m_PlayerMechanics_NumberKey4;
        public InputAction @NumberKey5 => m_Wrapper.m_PlayerMechanics_NumberKey5;
        public InputAction @NumberKey6 => m_Wrapper.m_PlayerMechanics_NumberKey6;
        public InputAction @NumberKey7 => m_Wrapper.m_PlayerMechanics_NumberKey7;
        public InputAction @NumberKey8 => m_Wrapper.m_PlayerMechanics_NumberKey8;
        public InputAction @NumberKey9 => m_Wrapper.m_PlayerMechanics_NumberKey9;
        public InputAction @LockOn => m_Wrapper.m_PlayerMechanics_LockOn;
        public InputAction @FlipCameraAlignment => m_Wrapper.m_PlayerMechanics_FlipCameraAlignment;
        public InputAction @PrimaryInteraction => m_Wrapper.m_PlayerMechanics_PrimaryInteraction;
        public InputAction @SecondaryInteraction => m_Wrapper.m_PlayerMechanics_SecondaryInteraction;
        public InputAction @TertiaryInteraction => m_Wrapper.m_PlayerMechanics_TertiaryInteraction;
        public InputAction @Sheath => m_Wrapper.m_PlayerMechanics_Sheath;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMechanics; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMechanicsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMechanicsActions instance)
        {
            if (m_Wrapper.m_PlayerMechanicsActionsCallbackInterface != null)
            {
                @MouseX.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseX;
                @MouseX.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseX;
                @MouseX.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseX;
                @MouseY.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseY;
                @MouseY.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseY;
                @MouseY.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseY;
                @CameraSwitch.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnCameraSwitch;
                @CameraSwitch.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnCameraSwitch;
                @CameraSwitch.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnCameraSwitch;
                @ToggleBuildMode.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnToggleBuildMode;
                @ToggleBuildMode.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnToggleBuildMode;
                @ToggleBuildMode.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnToggleBuildMode;
                @MouseScroll.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseScroll;
                @MouseScroll.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseScroll;
                @MouseScroll.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnMouseScroll;
                @NumberKey1.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey1;
                @NumberKey1.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey1;
                @NumberKey1.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey1;
                @NumberKey2.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey2;
                @NumberKey2.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey2;
                @NumberKey2.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey2;
                @NumberKey3.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey3;
                @NumberKey3.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey3;
                @NumberKey3.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey3;
                @NumberKey4.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey4;
                @NumberKey4.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey4;
                @NumberKey4.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey4;
                @NumberKey5.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey5;
                @NumberKey5.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey5;
                @NumberKey5.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey5;
                @NumberKey6.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey6;
                @NumberKey6.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey6;
                @NumberKey6.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey6;
                @NumberKey7.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey7;
                @NumberKey7.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey7;
                @NumberKey7.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey7;
                @NumberKey8.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey8;
                @NumberKey8.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey8;
                @NumberKey8.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey8;
                @NumberKey9.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey9;
                @NumberKey9.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey9;
                @NumberKey9.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnNumberKey9;
                @LockOn.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnLockOn;
                @LockOn.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnLockOn;
                @LockOn.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnLockOn;
                @FlipCameraAlignment.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnFlipCameraAlignment;
                @FlipCameraAlignment.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnFlipCameraAlignment;
                @FlipCameraAlignment.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnFlipCameraAlignment;
                @PrimaryInteraction.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnPrimaryInteraction;
                @PrimaryInteraction.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnPrimaryInteraction;
                @PrimaryInteraction.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnPrimaryInteraction;
                @SecondaryInteraction.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnSecondaryInteraction;
                @SecondaryInteraction.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnSecondaryInteraction;
                @SecondaryInteraction.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnSecondaryInteraction;
                @TertiaryInteraction.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnTertiaryInteraction;
                @TertiaryInteraction.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnTertiaryInteraction;
                @TertiaryInteraction.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnTertiaryInteraction;
                @Sheath.started -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnSheath;
                @Sheath.performed -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnSheath;
                @Sheath.canceled -= m_Wrapper.m_PlayerMechanicsActionsCallbackInterface.OnSheath;
            }
            m_Wrapper.m_PlayerMechanicsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseX.started += instance.OnMouseX;
                @MouseX.performed += instance.OnMouseX;
                @MouseX.canceled += instance.OnMouseX;
                @MouseY.started += instance.OnMouseY;
                @MouseY.performed += instance.OnMouseY;
                @MouseY.canceled += instance.OnMouseY;
                @CameraSwitch.started += instance.OnCameraSwitch;
                @CameraSwitch.performed += instance.OnCameraSwitch;
                @CameraSwitch.canceled += instance.OnCameraSwitch;
                @ToggleBuildMode.started += instance.OnToggleBuildMode;
                @ToggleBuildMode.performed += instance.OnToggleBuildMode;
                @ToggleBuildMode.canceled += instance.OnToggleBuildMode;
                @MouseScroll.started += instance.OnMouseScroll;
                @MouseScroll.performed += instance.OnMouseScroll;
                @MouseScroll.canceled += instance.OnMouseScroll;
                @NumberKey1.started += instance.OnNumberKey1;
                @NumberKey1.performed += instance.OnNumberKey1;
                @NumberKey1.canceled += instance.OnNumberKey1;
                @NumberKey2.started += instance.OnNumberKey2;
                @NumberKey2.performed += instance.OnNumberKey2;
                @NumberKey2.canceled += instance.OnNumberKey2;
                @NumberKey3.started += instance.OnNumberKey3;
                @NumberKey3.performed += instance.OnNumberKey3;
                @NumberKey3.canceled += instance.OnNumberKey3;
                @NumberKey4.started += instance.OnNumberKey4;
                @NumberKey4.performed += instance.OnNumberKey4;
                @NumberKey4.canceled += instance.OnNumberKey4;
                @NumberKey5.started += instance.OnNumberKey5;
                @NumberKey5.performed += instance.OnNumberKey5;
                @NumberKey5.canceled += instance.OnNumberKey5;
                @NumberKey6.started += instance.OnNumberKey6;
                @NumberKey6.performed += instance.OnNumberKey6;
                @NumberKey6.canceled += instance.OnNumberKey6;
                @NumberKey7.started += instance.OnNumberKey7;
                @NumberKey7.performed += instance.OnNumberKey7;
                @NumberKey7.canceled += instance.OnNumberKey7;
                @NumberKey8.started += instance.OnNumberKey8;
                @NumberKey8.performed += instance.OnNumberKey8;
                @NumberKey8.canceled += instance.OnNumberKey8;
                @NumberKey9.started += instance.OnNumberKey9;
                @NumberKey9.performed += instance.OnNumberKey9;
                @NumberKey9.canceled += instance.OnNumberKey9;
                @LockOn.started += instance.OnLockOn;
                @LockOn.performed += instance.OnLockOn;
                @LockOn.canceled += instance.OnLockOn;
                @FlipCameraAlignment.started += instance.OnFlipCameraAlignment;
                @FlipCameraAlignment.performed += instance.OnFlipCameraAlignment;
                @FlipCameraAlignment.canceled += instance.OnFlipCameraAlignment;
                @PrimaryInteraction.started += instance.OnPrimaryInteraction;
                @PrimaryInteraction.performed += instance.OnPrimaryInteraction;
                @PrimaryInteraction.canceled += instance.OnPrimaryInteraction;
                @SecondaryInteraction.started += instance.OnSecondaryInteraction;
                @SecondaryInteraction.performed += instance.OnSecondaryInteraction;
                @SecondaryInteraction.canceled += instance.OnSecondaryInteraction;
                @TertiaryInteraction.started += instance.OnTertiaryInteraction;
                @TertiaryInteraction.performed += instance.OnTertiaryInteraction;
                @TertiaryInteraction.canceled += instance.OnTertiaryInteraction;
                @Sheath.started += instance.OnSheath;
                @Sheath.performed += instance.OnSheath;
                @Sheath.canceled += instance.OnSheath;
            }
        }
    }
    public PlayerMechanicsActions @PlayerMechanics => new PlayerMechanicsActions(this);

    // GridBuilding
    private readonly InputActionMap m_GridBuilding;
    private IGridBuildingActions m_GridBuildingActionsCallbackInterface;
    private readonly InputAction m_GridBuilding_Demolish;
    private readonly InputAction m_GridBuilding_Build;
    private readonly InputAction m_GridBuilding_Rotate;
    private readonly InputAction m_GridBuilding_ToggleBuildMenu;
    public struct GridBuildingActions
    {
        private @PlayerControls m_Wrapper;
        public GridBuildingActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Demolish => m_Wrapper.m_GridBuilding_Demolish;
        public InputAction @Build => m_Wrapper.m_GridBuilding_Build;
        public InputAction @Rotate => m_Wrapper.m_GridBuilding_Rotate;
        public InputAction @ToggleBuildMenu => m_Wrapper.m_GridBuilding_ToggleBuildMenu;
        public InputActionMap Get() { return m_Wrapper.m_GridBuilding; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GridBuildingActions set) { return set.Get(); }
        public void SetCallbacks(IGridBuildingActions instance)
        {
            if (m_Wrapper.m_GridBuildingActionsCallbackInterface != null)
            {
                @Demolish.started -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnDemolish;
                @Demolish.performed -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnDemolish;
                @Demolish.canceled -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnDemolish;
                @Build.started -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnBuild;
                @Build.performed -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnBuild;
                @Build.canceled -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnBuild;
                @Rotate.started -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnRotate;
                @ToggleBuildMenu.started -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnToggleBuildMenu;
                @ToggleBuildMenu.performed -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnToggleBuildMenu;
                @ToggleBuildMenu.canceled -= m_Wrapper.m_GridBuildingActionsCallbackInterface.OnToggleBuildMenu;
            }
            m_Wrapper.m_GridBuildingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Demolish.started += instance.OnDemolish;
                @Demolish.performed += instance.OnDemolish;
                @Demolish.canceled += instance.OnDemolish;
                @Build.started += instance.OnBuild;
                @Build.performed += instance.OnBuild;
                @Build.canceled += instance.OnBuild;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @ToggleBuildMenu.started += instance.OnToggleBuildMenu;
                @ToggleBuildMenu.performed += instance.OnToggleBuildMenu;
                @ToggleBuildMenu.canceled += instance.OnToggleBuildMenu;
            }
        }
    }
    public GridBuildingActions @GridBuilding => new GridBuildingActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse + Keyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    public interface IUIActions
    {
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
    public interface IGroundMovementActions
    {
        void OnHorizontalMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
    }
    public interface IPlayerMechanicsActions
    {
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnCameraSwitch(InputAction.CallbackContext context);
        void OnToggleBuildMode(InputAction.CallbackContext context);
        void OnMouseScroll(InputAction.CallbackContext context);
        void OnNumberKey1(InputAction.CallbackContext context);
        void OnNumberKey2(InputAction.CallbackContext context);
        void OnNumberKey3(InputAction.CallbackContext context);
        void OnNumberKey4(InputAction.CallbackContext context);
        void OnNumberKey5(InputAction.CallbackContext context);
        void OnNumberKey6(InputAction.CallbackContext context);
        void OnNumberKey7(InputAction.CallbackContext context);
        void OnNumberKey8(InputAction.CallbackContext context);
        void OnNumberKey9(InputAction.CallbackContext context);
        void OnLockOn(InputAction.CallbackContext context);
        void OnFlipCameraAlignment(InputAction.CallbackContext context);
        void OnPrimaryInteraction(InputAction.CallbackContext context);
        void OnSecondaryInteraction(InputAction.CallbackContext context);
        void OnTertiaryInteraction(InputAction.CallbackContext context);
        void OnSheath(InputAction.CallbackContext context);
    }
    public interface IGridBuildingActions
    {
        void OnDemolish(InputAction.CallbackContext context);
        void OnBuild(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnToggleBuildMenu(InputAction.CallbackContext context);
    }
}
